# Refer to https://manpages.debian.org/bookworm/live-config-doc/live-config.7.en.html
LIVE_USER_DEFAULT_GROUPS=audio,cdrom,dip,floppy,video,plugdev,netdev,powerdev,scanner,bluetooth,fuse
# get keyboard model - https://superuser.com/questions/1300091/show-current-keyboard-layout
LIVE_KEYBOARD_MODEL=pc105
LIVE_LOCALES=C.UTF-8